// Generated automatically by nearley, version 2.20.1
// http://github.com/Hardmath123/nearley
function id(x) { return x[0]; }
let Lexer = undefined;
let ParserRules = [
    {"name": "observation$ebnf$1", "symbols": []},
    {"name": "observation$ebnf$1", "symbols": ["observation$ebnf$1", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "observation$ebnf$2", "symbols": ["break"]},
    {"name": "observation$ebnf$2", "symbols": ["observation$ebnf$2", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "observation$ebnf$3", "symbols": []},
    {"name": "observation$ebnf$3$subexpression$1$ebnf$1", "symbols": ["break"]},
    {"name": "observation$ebnf$3$subexpression$1$ebnf$1", "symbols": ["observation$ebnf$3$subexpression$1$ebnf$1", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "observation$ebnf$3$subexpression$1", "symbols": ["optional", "observation$ebnf$3$subexpression$1$ebnf$1"]},
    {"name": "observation$ebnf$3", "symbols": ["observation$ebnf$3", "observation$ebnf$3$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "observation$ebnf$4", "symbols": []},
    {"name": "observation$ebnf$4", "symbols": ["observation$ebnf$4", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "observation", "symbols": ["observation$ebnf$1", "required", "observation$ebnf$2", "observation$ebnf$3", "sights", "observation$ebnf$4"], "postprocess": d=>d[1].concat(d[3].map(v=>v[0][0])).concat(d[4])},
    {"name": "required$ebnf$1", "symbols": ["break"]},
    {"name": "required$ebnf$1", "symbols": ["required$ebnf$1", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "required", "symbols": ["date", "required$ebnf$1", "height"], "postprocess": d=> [d[0],d[2]]},
    {"name": "required$ebnf$2", "symbols": ["break"]},
    {"name": "required$ebnf$2", "symbols": ["required$ebnf$2", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "required", "symbols": ["height", "required$ebnf$2", "date"], "postprocess": d=> [d[2],d[0]]},
    {"name": "optional", "symbols": ["zone"]},
    {"name": "optional", "symbols": ["method"]},
    {"name": "optional", "symbols": ["index_error"]},
    {"name": "optional", "symbols": ["watch_error"]},
    {"name": "optional", "symbols": ["refraction"]},
    {"name": "optional", "symbols": ["compare"]},
    {"name": "optional", "symbols": ["ded_reckoning"]},
    {"name": "optional", "symbols": ["heading"]},
    {"name": "optional", "symbols": ["speed"]},
    {"name": "date$subexpression$1", "symbols": [/[dD]/, /[aA]/, /[tT]/, /[eE]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "date$ebnf$1", "symbols": ["sep"]},
    {"name": "date$ebnf$1", "symbols": ["date$ebnf$1", "sep"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "date$ebnf$2", "symbols": ["sep"]},
    {"name": "date$ebnf$2", "symbols": ["date$ebnf$2", "sep"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "date", "symbols": ["_", "date$subexpression$1", "_", {"literal":":"}, "_", "int", "date$ebnf$1", "int", "date$ebnf$2", "int"], "postprocess": d=> ({"date":{"y":d[5],"m":d[7],"d":d[9]}})},
    {"name": "height", "symbols": ["_", "obsheight", "_", {"literal":":"}, "_", "float", "_", "meter"], "postprocess": d=> ({"height":d[5]})},
    {"name": "zone$ebnf$1$subexpression$1", "symbols": [/[tT]/, /[iI]/, /[mM]/, /[eE]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "zone$ebnf$1", "symbols": ["zone$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "zone$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "zone$subexpression$1", "symbols": [/[zZ]/, /[oO]/, /[nN]/, /[eE]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "zone", "symbols": ["_", "zone$ebnf$1", "zone$subexpression$1", "_", {"literal":":"}, "tzone"], "postprocess": d=> ({"zone":d[5]})},
    {"name": "tzone$ebnf$1", "symbols": ["utc"], "postprocess": id},
    {"name": "tzone$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "tzone$subexpression$1", "symbols": [{"literal":"+"}]},
    {"name": "tzone$subexpression$1", "symbols": [{"literal":"-"}]},
    {"name": "tzone", "symbols": ["_", "tzone$ebnf$1", "tzone$subexpression$1", "zoffset"], "postprocess": d=> parseInt(`${d[2]}${d[3]}`,10)},
    {"name": "zoffset", "symbols": [{"literal":"1"}, /[0-2]/], "postprocess": ([a,b])=> `${a}${b}`},
    {"name": "zoffset$ebnf$1", "symbols": [{"literal":"0"}], "postprocess": id},
    {"name": "zoffset$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "zoffset", "symbols": ["zoffset$ebnf$1", /[0-9]/], "postprocess": ([a,b])=>     `${b}`},
    {"name": "method$subexpression$1", "symbols": [/[mM]/, /[eE]/, /[tT]/, /[hH]/, /[oO]/, /[dD]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "method", "symbols": ["_", "method$subexpression$1", "_", {"literal":":"}, "_", "methodtype"], "postprocess": d=> ({"method":d[5][0]})},
    {"name": "index_error$ebnf$1$subexpression$1", "symbols": [{"literal":"+"}]},
    {"name": "index_error$ebnf$1$subexpression$1", "symbols": [{"literal":"-"}]},
    {"name": "index_error$ebnf$1", "symbols": ["index_error$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "index_error$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "index_error$ebnf$2", "symbols": []},
    {"name": "index_error$ebnf$2", "symbols": ["index_error$ebnf$2", "sep"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "index_error", "symbols": ["_", "ie", "_", {"literal":":"}, "_", "index_error$ebnf$1", "decminsec", "index_error$ebnf$2"], "postprocess": d=> ({"index":d[6]*("-"==d[5]?-1:1)})},
    {"name": "watch_error$ebnf$1", "symbols": []},
    {"name": "watch_error$ebnf$1", "symbols": ["watch_error$ebnf$1", "sep"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "watch_error", "symbols": ["_", "we", "_", {"literal":":"}, "_", "decminsec", "watch_error$ebnf$1"], "postprocess": d=> ({"watch":d[5]})},
    {"name": "refraction$subexpression$1", "symbols": [/[rR]/, /[eE]/, /[fF]/, /[rR]/, /[aA]/, /[cC]/, /[tT]/, /[iI]/, /[oO]/, /[nN]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "refraction$subexpression$2", "symbols": [/[sS]/, /[tT]/, /[aA]/, /[nN]/, /[dD]/, /[aA]/, /[rR]/, /[dD]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "refraction", "symbols": ["_", "refraction$subexpression$1", "_", {"literal":":"}, "_", "refraction$subexpression$2"], "postprocess": d=> ({"temp":10  ,"press":1010})},
    {"name": "refraction$ebnf$1", "symbols": ["break"]},
    {"name": "refraction$ebnf$1", "symbols": ["refraction$ebnf$1", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "refraction", "symbols": ["temperature", "refraction$ebnf$1", "pressure"], "postprocess": d=> ({"temp":d[0],"press":d[2]})},
    {"name": "refraction$ebnf$2", "symbols": ["break"]},
    {"name": "refraction$ebnf$2", "symbols": ["refraction$ebnf$2", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "refraction", "symbols": ["pressure", "refraction$ebnf$2", "temperature"], "postprocess": d=> ({"temp":d[2],"press":d[0]})},
    {"name": "temperature$subexpression$1", "symbols": [/[tT]/, /[eE]/, /[mM]/, /[pP]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "temperature$ebnf$1$subexpression$1", "symbols": [/[eE]/, /[rR]/, /[aA]/, /[tT]/, /[uU]/, /[rR]/, /[eE]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "temperature$ebnf$1", "symbols": ["temperature$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "temperature$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "temperature", "symbols": ["_", "temperature$subexpression$1", "temperature$ebnf$1", "_", {"literal":":"}, "_", "float", "_", "celsius"], "postprocess": d=> parseFloat(d[6])},
    {"name": "pressure$subexpression$1", "symbols": [/[pP]/, /[rR]/, /[eE]/, /[sS]/, /[sS]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "pressure$ebnf$1$subexpression$1", "symbols": [/[uU]/, /[rR]/, /[eE]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "pressure$ebnf$1", "symbols": ["pressure$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "pressure$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pressure", "symbols": ["_", "pressure$subexpression$1", "pressure$ebnf$1", "_", {"literal":":"}, "_", "float", "_", "mbar"], "postprocess": d=> parseFloat(d[6])},
    {"name": "compare$subexpression$1", "symbols": [/[cC]/, /[oO]/, /[mM]/, /[pP]/, /[aA]/, /[rR]/, /[eE]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "compare", "symbols": ["_", "compare$subexpression$1", "_", {"literal":":"}, "_", "lat", "_", {"literal":","}, "_", "lon"], "postprocess": d=> ({"compare":[d[5],d[9]]})},
    {"name": "compare$subexpression$2", "symbols": [/[cC]/, /[oO]/, /[mM]/, /[pP]/, /[aA]/, /[rR]/, /[eE]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "compare$ebnf$1", "symbols": ["break"]},
    {"name": "compare$ebnf$1", "symbols": ["compare$ebnf$1", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "compare", "symbols": ["_", "compare$subexpression$2", "_", {"literal":":"}, "compare$ebnf$1", "latlon"], "postprocess": d=> ({"compare":d[5]})},
    {"name": "ded_reckoning", "symbols": ["_", "dr", "_", {"literal":":"}, "_", "lat", "_", {"literal":","}, "_", "lon"], "postprocess": d=> ({"dr":[d[5],d[9]]})},
    {"name": "ded_reckoning$ebnf$1", "symbols": ["break"]},
    {"name": "ded_reckoning$ebnf$1", "symbols": ["ded_reckoning$ebnf$1", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "ded_reckoning", "symbols": ["_", "dr", "_", {"literal":":"}, "ded_reckoning$ebnf$1", "latlon"], "postprocess": d=> ({"dr":d[5]})},
    {"name": "heading", "symbols": ["_", "bearing", "_", {"literal":":"}, "_", "deg360"], "postprocess": d=> ({"bear":d[5]})},
    {"name": "speed$subexpression$1", "symbols": [/[sS]/, /[pP]/, /[eE]/, /[eE]/, /[dD]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "speed", "symbols": ["_", "speed$subexpression$1", "_", {"literal":":"}, "_", "float", "_", "knot"], "postprocess": d=> ({"speed":d[5]})},
    {"name": "sights$ebnf$1", "symbols": ["break"]},
    {"name": "sights$ebnf$1", "symbols": ["sights$ebnf$1", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "sights$ebnf$2", "symbols": ["break"]},
    {"name": "sights$ebnf$2", "symbols": ["sights$ebnf$2", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "sights", "symbols": ["sight", "sights$ebnf$1", "sight", "sights$ebnf$2", "sight"], "postprocess": d=> [d[0],d[2],d[4]]},
    {"name": "sights$ebnf$3", "symbols": ["break"]},
    {"name": "sights$ebnf$3", "symbols": ["sights$ebnf$3", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "sights$ebnf$4", "symbols": ["break"]},
    {"name": "sights$ebnf$4", "symbols": ["sights$ebnf$4", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "sights", "symbols": ["sight", "sights$ebnf$3", "sight", "sights$ebnf$4", "landmark"], "postprocess": d=> [d[0],d[2],d[4]]},
    {"name": "sights$ebnf$5", "symbols": ["break"]},
    {"name": "sights$ebnf$5", "symbols": ["sights$ebnf$5", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "sights$ebnf$6", "symbols": ["break"]},
    {"name": "sights$ebnf$6", "symbols": ["sights$ebnf$6", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "sights", "symbols": ["sight", "sights$ebnf$5", "landmark", "sights$ebnf$6", "sight"], "postprocess": d=> [d[0],d[4],d[2]]},
    {"name": "sights$ebnf$7", "symbols": ["break"]},
    {"name": "sights$ebnf$7", "symbols": ["sights$ebnf$7", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "sights$ebnf$8", "symbols": ["break"]},
    {"name": "sights$ebnf$8", "symbols": ["sights$ebnf$8", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "sights", "symbols": ["landmark", "sights$ebnf$7", "sight", "sights$ebnf$8", "sight"], "postprocess": d=> [d[2],d[4],d[0]]},
    {"name": "sight$ebnf$1", "symbols": ["break"]},
    {"name": "sight$ebnf$1", "symbols": ["sight$ebnf$1", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "sight$ebnf$2", "symbols": ["break"]},
    {"name": "sight$ebnf$2", "symbols": ["sight$ebnf$2", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "sight", "symbols": ["star", "sight$ebnf$1", "time", "sight$ebnf$2", "angle"], "postprocess": d=> ({"star":d[0],"time":d[2],"angle":d[4]})},
    {"name": "sight$ebnf$3", "symbols": ["break"]},
    {"name": "sight$ebnf$3", "symbols": ["sight$ebnf$3", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "sight$ebnf$4", "symbols": ["break"]},
    {"name": "sight$ebnf$4", "symbols": ["sight$ebnf$4", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "sight", "symbols": ["star", "sight$ebnf$3", "angle", "sight$ebnf$4", "time"], "postprocess": d=> ({"star":d[0],"time":d[4],"angle":d[2]})},
    {"name": "landmark$ebnf$1", "symbols": ["break"]},
    {"name": "landmark$ebnf$1", "symbols": ["landmark$ebnf$1", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "landmark$ebnf$2", "symbols": ["break"]},
    {"name": "landmark$ebnf$2", "symbols": ["landmark$ebnf$2", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "landmark$ebnf$3", "symbols": ["break"]},
    {"name": "landmark$ebnf$3", "symbols": ["landmark$ebnf$3", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "landmark", "symbols": ["markname", "landmark$ebnf$1", "latitude", "landmark$ebnf$2", "longitude", "landmark$ebnf$3", "distance"], "postprocess": d=> ({"mark":d[0],"lat":d[2].lat,"lon":d[4].lon,"dist":d[6]})},
    {"name": "landmark$ebnf$4", "symbols": ["break"]},
    {"name": "landmark$ebnf$4", "symbols": ["landmark$ebnf$4", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "landmark$ebnf$5", "symbols": ["break"]},
    {"name": "landmark$ebnf$5", "symbols": ["landmark$ebnf$5", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "landmark$ebnf$6", "symbols": ["break"]},
    {"name": "landmark$ebnf$6", "symbols": ["landmark$ebnf$6", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "landmark", "symbols": ["markname", "landmark$ebnf$4", "longitude", "landmark$ebnf$5", "latitude", "landmark$ebnf$6", "distance"], "postprocess": d=> ({"mark":d[0],"lat":d[4].lat,"lon":d[2].lon,"dist":d[6]})},
    {"name": "landmark$ebnf$7", "symbols": ["break"]},
    {"name": "landmark$ebnf$7", "symbols": ["landmark$ebnf$7", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "landmark$ebnf$8", "symbols": ["break"]},
    {"name": "landmark$ebnf$8", "symbols": ["landmark$ebnf$8", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "landmark$ebnf$9", "symbols": ["break"]},
    {"name": "landmark$ebnf$9", "symbols": ["landmark$ebnf$9", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "landmark", "symbols": ["markname", "landmark$ebnf$7", "distance", "landmark$ebnf$8", "latitude", "landmark$ebnf$9", "longitude"], "postprocess": d=> ({"mark":d[0],"lat":d[4].lat,"lon":d[6].lon,"dist":d[2]})},
    {"name": "landmark$ebnf$10", "symbols": ["break"]},
    {"name": "landmark$ebnf$10", "symbols": ["landmark$ebnf$10", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "landmark$ebnf$11", "symbols": ["break"]},
    {"name": "landmark$ebnf$11", "symbols": ["landmark$ebnf$11", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "landmark$ebnf$12", "symbols": ["break"]},
    {"name": "landmark$ebnf$12", "symbols": ["landmark$ebnf$12", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "landmark", "symbols": ["markname", "landmark$ebnf$10", "distance", "landmark$ebnf$11", "longitude", "landmark$ebnf$12", "latitude"], "postprocess": d=> ({"mark":d[0],"lat":d[6].lat,"lon":d[4].lon,"dist":d[2]})},
    {"name": "landmark$ebnf$13", "symbols": ["break"]},
    {"name": "landmark$ebnf$13", "symbols": ["landmark$ebnf$13", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "landmark$ebnf$14", "symbols": ["break"]},
    {"name": "landmark$ebnf$14", "symbols": ["landmark$ebnf$14", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "landmark$ebnf$15", "symbols": ["break"]},
    {"name": "landmark$ebnf$15", "symbols": ["landmark$ebnf$15", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "landmark", "symbols": ["markname", "landmark$ebnf$13", "latitude", "landmark$ebnf$14", "distance", "landmark$ebnf$15", "longitude"], "postprocess": d=> ({"mark":d[0],"lat":d[2].lat,"lon":d[6].lon,"dist":d[4]})},
    {"name": "landmark$ebnf$16", "symbols": ["break"]},
    {"name": "landmark$ebnf$16", "symbols": ["landmark$ebnf$16", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "landmark$ebnf$17", "symbols": ["break"]},
    {"name": "landmark$ebnf$17", "symbols": ["landmark$ebnf$17", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "landmark$ebnf$18", "symbols": ["break"]},
    {"name": "landmark$ebnf$18", "symbols": ["landmark$ebnf$18", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "landmark", "symbols": ["markname", "landmark$ebnf$16", "longitude", "landmark$ebnf$17", "distance", "landmark$ebnf$18", "latitude"], "postprocess": d=> ({"mark":d[0],"lat":d[6].lat,"lon":d[2].lon,"dist":d[4]})},
    {"name": "star", "symbols": ["_", "object", "_", {"literal":":"}, "_", "word"], "postprocess": d=> d[5]},
    {"name": "time$subexpression$1", "symbols": [/[tT]/, /[iI]/, /[mM]/, /[eE]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "time", "symbols": ["_", "time$subexpression$1", "_", {"literal":":"}, "_", "hhmmss"], "postprocess": d=> d[5]},
    {"name": "angle$ebnf$1$subexpression$1", "symbols": [{"literal":"+"}]},
    {"name": "angle$ebnf$1$subexpression$1", "symbols": [{"literal":"-"}]},
    {"name": "angle$ebnf$1", "symbols": ["angle$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "angle$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "angle", "symbols": ["_", "alt", "_", {"literal":":"}, "_", "angle$ebnf$1", "deg90"], "postprocess": d=> ({"sign":("-"==d[5])?-1:1,"deg":d[6]})},
    {"name": "markname$ebnf$1$subexpression$1", "symbols": [/[lL]/, /[aA]/, /[nN]/, /[dD]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "markname$ebnf$1", "symbols": ["markname$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "markname$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "markname$subexpression$1", "symbols": [/[mM]/, /[aA]/, /[rR]/, /[kK]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "markname", "symbols": ["_", "markname$ebnf$1", "markname$subexpression$1", "_", {"literal":":"}, "_", "word"], "postprocess": d=> d[6]},
    {"name": "distance$subexpression$1", "symbols": [/[dD]/, /[iI]/, /[sS]/, /[tT]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "distance$ebnf$1$subexpression$1", "symbols": [/[aA]/, /[nN]/, /[cC]/, /[eE]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "distance$ebnf$1", "symbols": ["distance$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "distance$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "distance", "symbols": ["_", "distance$subexpression$1", "distance$ebnf$1", "_", {"literal":":"}, "_", "float", "_", "km"], "postprocess": d=> d[6]},
    {"name": "latlon$ebnf$1", "symbols": ["break"]},
    {"name": "latlon$ebnf$1", "symbols": ["latlon$ebnf$1", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "latlon", "symbols": ["latitude", "latlon$ebnf$1", "longitude"], "postprocess": d=> [d[0],d[2]]},
    {"name": "latlon$ebnf$2", "symbols": ["break"]},
    {"name": "latlon$ebnf$2", "symbols": ["latlon$ebnf$2", "break"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "latlon", "symbols": ["longitude", "latlon$ebnf$2", "latitude"], "postprocess": d=> [d[2],d[0]]},
    {"name": "latitude$subexpression$1", "symbols": [/[lL]/, /[aA]/, /[tT]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "latitude$ebnf$1$subexpression$1", "symbols": [/[iI]/, /[tT]/, /[uU]/, /[dD]/, /[eE]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "latitude$ebnf$1", "symbols": ["latitude$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "latitude$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "latitude", "symbols": ["_", "latitude$subexpression$1", "latitude$ebnf$1", "_", {"literal":":"}, "_", "lat"], "postprocess": d=> d[6]},
    {"name": "longitude$subexpression$1", "symbols": [/[lL]/, /[oO]/, /[nN]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "longitude$ebnf$1$subexpression$1", "symbols": [/[gG]/, /[iI]/, /[tT]/, /[uU]/, /[dD]/, /[eE]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "longitude$ebnf$1", "symbols": ["longitude$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "longitude$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "longitude", "symbols": ["_", "longitude$subexpression$1", "longitude$ebnf$1", "_", {"literal":":"}, "_", "lon"], "postprocess": d=> d[6]},
    {"name": "lat$ebnf$1$subexpression$1", "symbols": [{"literal":"+"}]},
    {"name": "lat$ebnf$1$subexpression$1", "symbols": [{"literal":"-"}]},
    {"name": "lat$ebnf$1", "symbols": ["lat$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "lat$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "lat", "symbols": ["lat$ebnf$1", "deg90"], "postprocess": d=> ({"lat":{"sign":("-"==d[0])           ?-1:1,"deg":d[1]}})},
    {"name": "lat$ebnf$2$subexpression$1$subexpression$1", "symbols": [/[nN]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "lat$ebnf$2$subexpression$1", "symbols": ["lat$ebnf$2$subexpression$1$subexpression$1"]},
    {"name": "lat$ebnf$2$subexpression$1$subexpression$2", "symbols": [/[sS]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "lat$ebnf$2$subexpression$1", "symbols": ["lat$ebnf$2$subexpression$1$subexpression$2"]},
    {"name": "lat$ebnf$2", "symbols": ["lat$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "lat$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "lat", "symbols": ["deg90", "_", "lat$ebnf$2"], "postprocess": d=> ({"lat":{"sign":("s"==d[2]||"S"==d[2])?-1:1,"deg":d[0]}})},
    {"name": "lon$ebnf$1$subexpression$1", "symbols": [{"literal":"+"}]},
    {"name": "lon$ebnf$1$subexpression$1", "symbols": [{"literal":"-"}]},
    {"name": "lon$ebnf$1", "symbols": ["lon$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "lon$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "lon", "symbols": ["lon$ebnf$1", "deg180"], "postprocess": d=> ({"lon":{"sign":("-"==d[0])           ?-1:1,"deg":d[1]}})},
    {"name": "lon$ebnf$2$subexpression$1$subexpression$1", "symbols": [/[eE]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "lon$ebnf$2$subexpression$1", "symbols": ["lon$ebnf$2$subexpression$1$subexpression$1"]},
    {"name": "lon$ebnf$2$subexpression$1$subexpression$2", "symbols": [/[wW]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "lon$ebnf$2$subexpression$1", "symbols": ["lon$ebnf$2$subexpression$1$subexpression$2"]},
    {"name": "lon$ebnf$2", "symbols": ["lon$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "lon$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "lon", "symbols": ["deg180", "_", "lon$ebnf$2"], "postprocess": d=> ({"lon":{"sign":("w"==d[2]||"W"==d[2])?-1:1,"deg":d[0]}})},
    {"name": "deg360$ebnf$1", "symbols": ["sep"]},
    {"name": "deg360$ebnf$1", "symbols": ["deg360$ebnf$1", "sep"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "deg360$ebnf$2", "symbols": ["sep"]},
    {"name": "deg360$ebnf$2", "symbols": ["deg360$ebnf$2", "sep"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "deg360$ebnf$3", "symbols": []},
    {"name": "deg360$ebnf$3", "symbols": ["deg360$ebnf$3", "sep"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "deg360", "symbols": ["decdeg360", "deg360$ebnf$1", "decminsec", "deg360$ebnf$2", "decminsec", "deg360$ebnf$3"], "postprocess": d=> ({"d":d[0],"m":d[2],"s":d[4]})},
    {"name": "deg360$ebnf$4", "symbols": ["sep"]},
    {"name": "deg360$ebnf$4", "symbols": ["deg360$ebnf$4", "sep"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "deg360$ebnf$5", "symbols": []},
    {"name": "deg360$ebnf$5", "symbols": ["deg360$ebnf$5", "sep"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "deg360", "symbols": ["decdeg360", "deg360$ebnf$4", "decminsec", "deg360$ebnf$5"], "postprocess": d=> ({"d":d[0],"m":d[2],"s":0   })},
    {"name": "deg360$ebnf$6", "symbols": []},
    {"name": "deg360$ebnf$6", "symbols": ["deg360$ebnf$6", "sep"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "deg360", "symbols": ["decdeg360", "deg360$ebnf$6"], "postprocess": d=> ({"d":d[0],"m":0   ,"s":0   })},
    {"name": "deg180$ebnf$1", "symbols": ["sep"]},
    {"name": "deg180$ebnf$1", "symbols": ["deg180$ebnf$1", "sep"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "deg180$ebnf$2", "symbols": ["sep"]},
    {"name": "deg180$ebnf$2", "symbols": ["deg180$ebnf$2", "sep"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "deg180$ebnf$3", "symbols": []},
    {"name": "deg180$ebnf$3", "symbols": ["deg180$ebnf$3", "sep"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "deg180", "symbols": ["decdeg180", "deg180$ebnf$1", "decminsec", "deg180$ebnf$2", "decminsec", "deg180$ebnf$3"], "postprocess": d=> ({"d":d[0],"m":d[2],"s":d[4]})},
    {"name": "deg180$ebnf$4", "symbols": ["sep"]},
    {"name": "deg180$ebnf$4", "symbols": ["deg180$ebnf$4", "sep"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "deg180$ebnf$5", "symbols": []},
    {"name": "deg180$ebnf$5", "symbols": ["deg180$ebnf$5", "sep"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "deg180", "symbols": ["decdeg180", "deg180$ebnf$4", "decminsec", "deg180$ebnf$5"], "postprocess": d=> ({"d":d[0],"m":d[2],"s":0   })},
    {"name": "deg180$ebnf$6", "symbols": []},
    {"name": "deg180$ebnf$6", "symbols": ["deg180$ebnf$6", "sep"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "deg180", "symbols": ["decdeg180", "deg180$ebnf$6"], "postprocess": d=> ({"d":d[0],"m":0   ,"s":0   })},
    {"name": "deg90$ebnf$1", "symbols": ["sep"]},
    {"name": "deg90$ebnf$1", "symbols": ["deg90$ebnf$1", "sep"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "deg90$ebnf$2", "symbols": ["sep"]},
    {"name": "deg90$ebnf$2", "symbols": ["deg90$ebnf$2", "sep"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "deg90$ebnf$3", "symbols": []},
    {"name": "deg90$ebnf$3", "symbols": ["deg90$ebnf$3", "sep"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "deg90", "symbols": ["decdeg90", "deg90$ebnf$1", "decminsec", "deg90$ebnf$2", "decminsec", "deg90$ebnf$3"], "postprocess": d=> ({"d":d[0],"m":d[2],"s":d[4]})},
    {"name": "deg90$ebnf$4", "symbols": ["sep"]},
    {"name": "deg90$ebnf$4", "symbols": ["deg90$ebnf$4", "sep"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "deg90$ebnf$5", "symbols": []},
    {"name": "deg90$ebnf$5", "symbols": ["deg90$ebnf$5", "sep"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "deg90", "symbols": ["decdeg90", "deg90$ebnf$4", "decminsec", "deg90$ebnf$5"], "postprocess": d=> ({"d":d[0],"m":d[2],"s":0   })},
    {"name": "deg90$ebnf$6", "symbols": []},
    {"name": "deg90$ebnf$6", "symbols": ["deg90$ebnf$6", "sep"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "deg90", "symbols": ["decdeg90", "deg90$ebnf$6"], "postprocess": d=> ({"d":d[0],"m":0   ,"s":0   })},
    {"name": "hhmmss$ebnf$1", "symbols": ["sep"]},
    {"name": "hhmmss$ebnf$1", "symbols": ["hhmmss$ebnf$1", "sep"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "hhmmss$ebnf$2", "symbols": ["sep"]},
    {"name": "hhmmss$ebnf$2", "symbols": ["hhmmss$ebnf$2", "sep"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "hhmmss$ebnf$3", "symbols": []},
    {"name": "hhmmss$ebnf$3", "symbols": ["hhmmss$ebnf$3", "sep"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "hhmmss", "symbols": ["hour", "hhmmss$ebnf$1", "decminsec", "hhmmss$ebnf$2", "decminsec", "hhmmss$ebnf$3"], "postprocess": d=> ({"d":d[0],"m":d[2],"s":d[4]})},
    {"name": "hhmmss$ebnf$4", "symbols": ["sep"]},
    {"name": "hhmmss$ebnf$4", "symbols": ["hhmmss$ebnf$4", "sep"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "hhmmss$ebnf$5", "symbols": []},
    {"name": "hhmmss$ebnf$5", "symbols": ["hhmmss$ebnf$5", "sep"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "hhmmss", "symbols": ["hour", "hhmmss$ebnf$4", "decminsec", "hhmmss$ebnf$5"], "postprocess": d=> ({"d":d[0],"m":d[2],"s":0   })},
    {"name": "hhmmss$ebnf$6", "symbols": []},
    {"name": "hhmmss$ebnf$6", "symbols": ["hhmmss$ebnf$6", "sep"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "hhmmss", "symbols": ["hour", "hhmmss$ebnf$6"], "postprocess": d=> ({"d":d[0],"m":0   ,"s":0   })},
    {"name": "decdeg360$ebnf$1", "symbols": [{"literal":"0"}], "postprocess": id},
    {"name": "decdeg360$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decdeg360$string$1", "symbols": [{"literal":"3"}, {"literal":"6"}, {"literal":"0"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "decdeg360$ebnf$2$subexpression$1$ebnf$1", "symbols": []},
    {"name": "decdeg360$ebnf$2$subexpression$1$ebnf$1", "symbols": ["decdeg360$ebnf$2$subexpression$1$ebnf$1", {"literal":"0"}], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "decdeg360$ebnf$2$subexpression$1", "symbols": [{"literal":"."}, "decdeg360$ebnf$2$subexpression$1$ebnf$1"]},
    {"name": "decdeg360$ebnf$2", "symbols": ["decdeg360$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "decdeg360$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decdeg360", "symbols": ["decdeg360$ebnf$1", "decdeg360$string$1", "decdeg360$ebnf$2"], "postprocess": d=> 360.0},
    {"name": "decdeg360$ebnf$3", "symbols": [{"literal":"0"}], "postprocess": id},
    {"name": "decdeg360$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decdeg360$ebnf$4$subexpression$1$ebnf$1", "symbols": []},
    {"name": "decdeg360$ebnf$4$subexpression$1$ebnf$1", "symbols": ["decdeg360$ebnf$4$subexpression$1$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "decdeg360$ebnf$4$subexpression$1", "symbols": [{"literal":"."}, "decdeg360$ebnf$4$subexpression$1$ebnf$1"]},
    {"name": "decdeg360$ebnf$4", "symbols": ["decdeg360$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "decdeg360$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decdeg360", "symbols": ["decdeg360$ebnf$3", {"literal":"3"}, /[0-5]/, /[0-9]/, "decdeg360$ebnf$4"], "postprocess": d=> parseFloat(`${d[1]}${d[2]}${d[3]}.${(d[4]?d[4][1].join(''):'0')}`)},
    {"name": "decdeg360$ebnf$5", "symbols": [{"literal":"0"}], "postprocess": id},
    {"name": "decdeg360$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decdeg360$ebnf$6$subexpression$1$ebnf$1", "symbols": []},
    {"name": "decdeg360$ebnf$6$subexpression$1$ebnf$1", "symbols": ["decdeg360$ebnf$6$subexpression$1$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "decdeg360$ebnf$6$subexpression$1", "symbols": [{"literal":"."}, "decdeg360$ebnf$6$subexpression$1$ebnf$1"]},
    {"name": "decdeg360$ebnf$6", "symbols": ["decdeg360$ebnf$6$subexpression$1"], "postprocess": id},
    {"name": "decdeg360$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decdeg360", "symbols": ["decdeg360$ebnf$5", /[1-2]/, /[0-9]/, /[0-9]/, "decdeg360$ebnf$6"], "postprocess": d=> parseFloat(`${d[1]}${d[2]}${d[3]}.${(d[4]?d[4][1].join(''):'0')}`)},
    {"name": "decdeg360$ebnf$7", "symbols": [{"literal":"0"}], "postprocess": id},
    {"name": "decdeg360$ebnf$7", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decdeg360$ebnf$8", "symbols": [{"literal":"0"}], "postprocess": id},
    {"name": "decdeg360$ebnf$8", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decdeg360$ebnf$9$subexpression$1$ebnf$1", "symbols": []},
    {"name": "decdeg360$ebnf$9$subexpression$1$ebnf$1", "symbols": ["decdeg360$ebnf$9$subexpression$1$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "decdeg360$ebnf$9$subexpression$1", "symbols": [{"literal":"."}, "decdeg360$ebnf$9$subexpression$1$ebnf$1"]},
    {"name": "decdeg360$ebnf$9", "symbols": ["decdeg360$ebnf$9$subexpression$1"], "postprocess": id},
    {"name": "decdeg360$ebnf$9", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decdeg360", "symbols": ["decdeg360$ebnf$7", "decdeg360$ebnf$8", /[1-9]/, /[0-9]/, "decdeg360$ebnf$9"], "postprocess": d=> parseFloat(       `${d[2]}${d[3]}.${(d[4]?d[4][1].join(''):'0')}`)},
    {"name": "decdeg360$ebnf$10", "symbols": [{"literal":"0"}], "postprocess": id},
    {"name": "decdeg360$ebnf$10", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decdeg360$ebnf$11", "symbols": [{"literal":"0"}], "postprocess": id},
    {"name": "decdeg360$ebnf$11", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decdeg360$ebnf$12", "symbols": [{"literal":"0"}], "postprocess": id},
    {"name": "decdeg360$ebnf$12", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decdeg360$ebnf$13$subexpression$1$ebnf$1", "symbols": []},
    {"name": "decdeg360$ebnf$13$subexpression$1$ebnf$1", "symbols": ["decdeg360$ebnf$13$subexpression$1$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "decdeg360$ebnf$13$subexpression$1", "symbols": [{"literal":"."}, "decdeg360$ebnf$13$subexpression$1$ebnf$1"]},
    {"name": "decdeg360$ebnf$13", "symbols": ["decdeg360$ebnf$13$subexpression$1"], "postprocess": id},
    {"name": "decdeg360$ebnf$13", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decdeg360", "symbols": ["decdeg360$ebnf$10", "decdeg360$ebnf$11", "decdeg360$ebnf$12", /[0-9]/, "decdeg360$ebnf$13"], "postprocess": d=> parseFloat(              `${d[3]}.${(d[4]?d[4][1].join(''):'0')}`)},
    {"name": "decdeg180$ebnf$1", "symbols": [{"literal":"0"}], "postprocess": id},
    {"name": "decdeg180$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decdeg180$string$1", "symbols": [{"literal":"1"}, {"literal":"8"}, {"literal":"0"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "decdeg180$ebnf$2$subexpression$1$ebnf$1", "symbols": []},
    {"name": "decdeg180$ebnf$2$subexpression$1$ebnf$1", "symbols": ["decdeg180$ebnf$2$subexpression$1$ebnf$1", {"literal":"0"}], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "decdeg180$ebnf$2$subexpression$1", "symbols": [{"literal":"."}, "decdeg180$ebnf$2$subexpression$1$ebnf$1"]},
    {"name": "decdeg180$ebnf$2", "symbols": ["decdeg180$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "decdeg180$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decdeg180", "symbols": ["decdeg180$ebnf$1", "decdeg180$string$1", "decdeg180$ebnf$2"], "postprocess": d=> 180.0},
    {"name": "decdeg180$ebnf$3", "symbols": [{"literal":"0"}], "postprocess": id},
    {"name": "decdeg180$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decdeg180$ebnf$4$subexpression$1$ebnf$1", "symbols": []},
    {"name": "decdeg180$ebnf$4$subexpression$1$ebnf$1", "symbols": ["decdeg180$ebnf$4$subexpression$1$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "decdeg180$ebnf$4$subexpression$1", "symbols": [{"literal":"."}, "decdeg180$ebnf$4$subexpression$1$ebnf$1"]},
    {"name": "decdeg180$ebnf$4", "symbols": ["decdeg180$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "decdeg180$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decdeg180", "symbols": ["decdeg180$ebnf$3", {"literal":"1"}, /[0-7]/, /[0-9]/, "decdeg180$ebnf$4"], "postprocess": d=> parseFloat(`${d[1]}${d[2]}${d[3]}.${(d[4]?d[4][1].join(''):'0')}`)},
    {"name": "decdeg180$ebnf$5", "symbols": [{"literal":"0"}], "postprocess": id},
    {"name": "decdeg180$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decdeg180$ebnf$6", "symbols": [{"literal":"0"}], "postprocess": id},
    {"name": "decdeg180$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decdeg180$ebnf$7$subexpression$1$ebnf$1", "symbols": []},
    {"name": "decdeg180$ebnf$7$subexpression$1$ebnf$1", "symbols": ["decdeg180$ebnf$7$subexpression$1$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "decdeg180$ebnf$7$subexpression$1", "symbols": [{"literal":"."}, "decdeg180$ebnf$7$subexpression$1$ebnf$1"]},
    {"name": "decdeg180$ebnf$7", "symbols": ["decdeg180$ebnf$7$subexpression$1"], "postprocess": id},
    {"name": "decdeg180$ebnf$7", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decdeg180", "symbols": ["decdeg180$ebnf$5", "decdeg180$ebnf$6", /[1-9]/, /[0-9]/, "decdeg180$ebnf$7"], "postprocess": d=> parseFloat(       `${d[2]}${d[3]}.${(d[4]?d[4][1].join(''):'0')}`)},
    {"name": "decdeg180$ebnf$8", "symbols": [{"literal":"0"}], "postprocess": id},
    {"name": "decdeg180$ebnf$8", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decdeg180$ebnf$9", "symbols": [{"literal":"0"}], "postprocess": id},
    {"name": "decdeg180$ebnf$9", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decdeg180$ebnf$10", "symbols": [{"literal":"0"}], "postprocess": id},
    {"name": "decdeg180$ebnf$10", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decdeg180$ebnf$11$subexpression$1$ebnf$1", "symbols": []},
    {"name": "decdeg180$ebnf$11$subexpression$1$ebnf$1", "symbols": ["decdeg180$ebnf$11$subexpression$1$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "decdeg180$ebnf$11$subexpression$1", "symbols": [{"literal":"."}, "decdeg180$ebnf$11$subexpression$1$ebnf$1"]},
    {"name": "decdeg180$ebnf$11", "symbols": ["decdeg180$ebnf$11$subexpression$1"], "postprocess": id},
    {"name": "decdeg180$ebnf$11", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decdeg180", "symbols": ["decdeg180$ebnf$8", "decdeg180$ebnf$9", "decdeg180$ebnf$10", /[0-9]/, "decdeg180$ebnf$11"], "postprocess": d=> parseFloat(              `${d[3]}.${(d[4]?d[4][1].join(''):'0')}`)},
    {"name": "decdeg90$ebnf$1", "symbols": [{"literal":"0"}], "postprocess": id},
    {"name": "decdeg90$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decdeg90$string$1", "symbols": [{"literal":"9"}, {"literal":"0"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "decdeg90$ebnf$2$subexpression$1$ebnf$1", "symbols": []},
    {"name": "decdeg90$ebnf$2$subexpression$1$ebnf$1", "symbols": ["decdeg90$ebnf$2$subexpression$1$ebnf$1", {"literal":"0"}], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "decdeg90$ebnf$2$subexpression$1", "symbols": [{"literal":"."}, "decdeg90$ebnf$2$subexpression$1$ebnf$1"]},
    {"name": "decdeg90$ebnf$2", "symbols": ["decdeg90$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "decdeg90$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decdeg90", "symbols": ["decdeg90$ebnf$1", "decdeg90$string$1", "decdeg90$ebnf$2"], "postprocess": d=> 90.0},
    {"name": "decdeg90$ebnf$3", "symbols": [{"literal":"0"}], "postprocess": id},
    {"name": "decdeg90$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decdeg90$ebnf$4$subexpression$1$ebnf$1", "symbols": []},
    {"name": "decdeg90$ebnf$4$subexpression$1$ebnf$1", "symbols": ["decdeg90$ebnf$4$subexpression$1$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "decdeg90$ebnf$4$subexpression$1", "symbols": [{"literal":"."}, "decdeg90$ebnf$4$subexpression$1$ebnf$1"]},
    {"name": "decdeg90$ebnf$4", "symbols": ["decdeg90$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "decdeg90$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decdeg90", "symbols": ["decdeg90$ebnf$3", /[1-8]/, /[0-9]/, "decdeg90$ebnf$4"], "postprocess": d=> parseFloat(`${d[1]}${d[2]}.${(d[3]?d[3][1].join(''):'0')}`)},
    {"name": "decdeg90$ebnf$5", "symbols": [{"literal":"0"}], "postprocess": id},
    {"name": "decdeg90$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decdeg90$ebnf$6", "symbols": [{"literal":"0"}], "postprocess": id},
    {"name": "decdeg90$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decdeg90$ebnf$7$subexpression$1$ebnf$1", "symbols": []},
    {"name": "decdeg90$ebnf$7$subexpression$1$ebnf$1", "symbols": ["decdeg90$ebnf$7$subexpression$1$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "decdeg90$ebnf$7$subexpression$1", "symbols": [{"literal":"."}, "decdeg90$ebnf$7$subexpression$1$ebnf$1"]},
    {"name": "decdeg90$ebnf$7", "symbols": ["decdeg90$ebnf$7$subexpression$1"], "postprocess": id},
    {"name": "decdeg90$ebnf$7", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decdeg90", "symbols": ["decdeg90$ebnf$5", "decdeg90$ebnf$6", /[0-9]/, "decdeg90$ebnf$7"], "postprocess": d=> parseFloat(       `${d[2]}.${(d[3]?d[3][1].join(''):'0')}`)},
    {"name": "hour$ebnf$1$subexpression$1$ebnf$1", "symbols": []},
    {"name": "hour$ebnf$1$subexpression$1$ebnf$1", "symbols": ["hour$ebnf$1$subexpression$1$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "hour$ebnf$1$subexpression$1", "symbols": [{"literal":"."}, "hour$ebnf$1$subexpression$1$ebnf$1"]},
    {"name": "hour$ebnf$1", "symbols": ["hour$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "hour$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "hour", "symbols": [{"literal":"2"}, /[0-4]/, "hour$ebnf$1"], "postprocess": d=> parseFloat(`${d[0]}${d[1]}.${(d[2]?d[2][1].join(''):'0')}`)},
    {"name": "hour$ebnf$2$subexpression$1$ebnf$1", "symbols": []},
    {"name": "hour$ebnf$2$subexpression$1$ebnf$1", "symbols": ["hour$ebnf$2$subexpression$1$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "hour$ebnf$2$subexpression$1", "symbols": [{"literal":"."}, "hour$ebnf$2$subexpression$1$ebnf$1"]},
    {"name": "hour$ebnf$2", "symbols": ["hour$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "hour$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "hour", "symbols": [{"literal":"1"}, /[0-9]/, "hour$ebnf$2"], "postprocess": d=> parseFloat(`${d[0]}${d[1]}.${(d[2]?d[2][1].join(''):'0')}`)},
    {"name": "hour$ebnf$3", "symbols": [{"literal":"0"}], "postprocess": id},
    {"name": "hour$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "hour$ebnf$4$subexpression$1$ebnf$1", "symbols": []},
    {"name": "hour$ebnf$4$subexpression$1$ebnf$1", "symbols": ["hour$ebnf$4$subexpression$1$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "hour$ebnf$4$subexpression$1", "symbols": [{"literal":"."}, "hour$ebnf$4$subexpression$1$ebnf$1"]},
    {"name": "hour$ebnf$4", "symbols": ["hour$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "hour$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "hour", "symbols": ["hour$ebnf$3", /[0-9]/, "hour$ebnf$4"], "postprocess": d=> parseFloat(       `${d[1]}.${(d[2]?d[2][1].join(''):'0')}`)},
    {"name": "decminsec$ebnf$1", "symbols": [{"literal":"0"}], "postprocess": id},
    {"name": "decminsec$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decminsec$string$1", "symbols": [{"literal":"6"}, {"literal":"0"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "decminsec$ebnf$2$subexpression$1$ebnf$1", "symbols": []},
    {"name": "decminsec$ebnf$2$subexpression$1$ebnf$1", "symbols": ["decminsec$ebnf$2$subexpression$1$ebnf$1", {"literal":"0"}], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "decminsec$ebnf$2$subexpression$1", "symbols": [{"literal":"."}, "decminsec$ebnf$2$subexpression$1$ebnf$1"]},
    {"name": "decminsec$ebnf$2", "symbols": ["decminsec$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "decminsec$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decminsec", "symbols": ["decminsec$ebnf$1", "decminsec$string$1", "decminsec$ebnf$2"], "postprocess": d=> 60.0},
    {"name": "decminsec$ebnf$3", "symbols": [{"literal":"0"}], "postprocess": id},
    {"name": "decminsec$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decminsec$ebnf$4$subexpression$1$ebnf$1", "symbols": []},
    {"name": "decminsec$ebnf$4$subexpression$1$ebnf$1", "symbols": ["decminsec$ebnf$4$subexpression$1$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "decminsec$ebnf$4$subexpression$1", "symbols": [{"literal":"."}, "decminsec$ebnf$4$subexpression$1$ebnf$1"]},
    {"name": "decminsec$ebnf$4", "symbols": ["decminsec$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "decminsec$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decminsec", "symbols": ["decminsec$ebnf$3", /[1-5]/, /[0-9]/, "decminsec$ebnf$4"], "postprocess": d=> parseFloat(`${d[1]}${d[2]}.${(d[3]?d[3][1].join(''):'0')}`)},
    {"name": "decminsec$ebnf$5", "symbols": [{"literal":"0"}], "postprocess": id},
    {"name": "decminsec$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decminsec$ebnf$6", "symbols": [{"literal":"0"}], "postprocess": id},
    {"name": "decminsec$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decminsec$ebnf$7$subexpression$1$ebnf$1", "symbols": []},
    {"name": "decminsec$ebnf$7$subexpression$1$ebnf$1", "symbols": ["decminsec$ebnf$7$subexpression$1$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "decminsec$ebnf$7$subexpression$1", "symbols": [{"literal":"."}, "decminsec$ebnf$7$subexpression$1$ebnf$1"]},
    {"name": "decminsec$ebnf$7", "symbols": ["decminsec$ebnf$7$subexpression$1"], "postprocess": id},
    {"name": "decminsec$ebnf$7", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decminsec", "symbols": ["decminsec$ebnf$5", "decminsec$ebnf$6", /[0-9]/, "decminsec$ebnf$7"], "postprocess": d=> parseFloat(       `${d[2]}.${(d[3]?d[3][1].join(''):'0')}`)},
    {"name": "utc$subexpression$1", "symbols": [/[uU]/, /[tT]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "utc", "symbols": ["utc$subexpression$1"]},
    {"name": "utc$subexpression$2", "symbols": [/[uU]/, /[tT]/, /[cC]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "utc", "symbols": ["utc$subexpression$2"]},
    {"name": "utc$subexpression$3", "symbols": [/[gG]/, /[mM]/, /[tT]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "utc", "symbols": ["utc$subexpression$3"]},
    {"name": "methodtype$subexpression$1", "symbols": [/[sS]/, /[eE]/, /[xX]/, /[tT]/, /[aA]/, /[nN]/, /[tT]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "methodtype", "symbols": ["methodtype$subexpression$1"]},
    {"name": "methodtype$subexpression$2", "symbols": [/[bB]/, /[uU]/, /[bB]/, /[bB]/, /[lL]/, /[eE]/, {"literal":" "}, /[sS]/, /[eE]/, /[xX]/, /[tT]/, /[aA]/, /[nN]/, /[tT]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "methodtype", "symbols": ["methodtype$subexpression$2"]},
    {"name": "methodtype$subexpression$3", "symbols": [/[tT]/, /[hH]/, /[eE]/, /[oO]/, /[dD]/, /[oO]/, /[lL]/, /[iI]/, /[tT]/, /[eE]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "methodtype", "symbols": ["methodtype$subexpression$3"]},
    {"name": "methodtype$subexpression$4", "symbols": [/[cC]/, /[eE]/, /[lL]/, /[lL]/, /[pP]/, /[hH]/, /[oO]/, /[nN]/, /[eE]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "methodtype", "symbols": ["methodtype$subexpression$4"]},
    {"name": "meter$subexpression$1", "symbols": [/[mM]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "meter", "symbols": ["meter$subexpression$1"]},
    {"name": "meter$subexpression$2", "symbols": [/[mM]/, /[eE]/, /[tT]/, /[eE]/, /[rR]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "meter", "symbols": ["meter$subexpression$2"]},
    {"name": "meter$subexpression$3", "symbols": [/[mM]/, /[eE]/, /[tT]/, /[eE]/, /[rR]/, /[sS]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "meter", "symbols": ["meter$subexpression$3"]},
    {"name": "meter$subexpression$4", "symbols": [/[mM]/, /[eE]/, /[tT]/, /[rR]/, /[eE]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "meter", "symbols": ["meter$subexpression$4"]},
    {"name": "meter$subexpression$5", "symbols": [/[mM]/, /[eE]/, /[tT]/, /[rR]/, /[eE]/, /[sS]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "meter", "symbols": ["meter$subexpression$5"]},
    {"name": "obsheight$ebnf$1$subexpression$1$subexpression$1", "symbols": [/[eE]/, /[yY]/, /[eE]/, {"literal":" "}], "postprocess": function(d) {return d.join(""); }},
    {"name": "obsheight$ebnf$1$subexpression$1", "symbols": ["obsheight$ebnf$1$subexpression$1$subexpression$1"]},
    {"name": "obsheight$ebnf$1$subexpression$1$subexpression$2", "symbols": [/[oO]/, /[bB]/, /[sS]/, /[eE]/, /[rR]/, /[vV]/, /[eE]/, /[rR]/, {"literal":" "}], "postprocess": function(d) {return d.join(""); }},
    {"name": "obsheight$ebnf$1$subexpression$1", "symbols": ["obsheight$ebnf$1$subexpression$1$subexpression$2"]},
    {"name": "obsheight$ebnf$1$subexpression$1$subexpression$3", "symbols": [/[oO]/, /[bB]/, /[sS]/, {"literal":"."}, {"literal":" "}], "postprocess": function(d) {return d.join(""); }},
    {"name": "obsheight$ebnf$1$subexpression$1", "symbols": ["obsheight$ebnf$1$subexpression$1$subexpression$3"]},
    {"name": "obsheight$ebnf$1", "symbols": ["obsheight$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "obsheight$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "obsheight$subexpression$1", "symbols": [/[hH]/, /[eE]/, /[iI]/, /[gG]/, /[hH]/, /[tT]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "obsheight", "symbols": ["obsheight$ebnf$1", "obsheight$subexpression$1"]},
    {"name": "we$subexpression$1", "symbols": [/[wW]/, /[aA]/, /[tT]/, /[cC]/, /[hH]/, {"literal":" "}, /[eE]/, /[rR]/, /[rR]/, /[oO]/, /[rR]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "we", "symbols": ["we$subexpression$1"]},
    {"name": "we$subexpression$2", "symbols": [/[wW]/, /[aA]/, /[tT]/, /[cC]/, /[hH]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "we", "symbols": ["we$subexpression$2"]},
    {"name": "we$subexpression$3", "symbols": [/[wW]/, /[eE]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "we", "symbols": ["we$subexpression$3"]},
    {"name": "ie$subexpression$1", "symbols": [/[iI]/, /[nN]/, /[dD]/, /[eE]/, /[xX]/, {"literal":" "}, /[eE]/, /[rR]/, /[rR]/, /[oO]/, /[rR]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "ie", "symbols": ["ie$subexpression$1"]},
    {"name": "ie$subexpression$2", "symbols": [/[iI]/, /[nN]/, /[dD]/, /[eE]/, /[xX]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "ie", "symbols": ["ie$subexpression$2"]},
    {"name": "ie$subexpression$3", "symbols": [/[iI]/, /[eE]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "ie", "symbols": ["ie$subexpression$3"]},
    {"name": "celsius", "symbols": [{"literal":"°"}]},
    {"name": "celsius$subexpression$1", "symbols": [{"literal":"°"}, /[cC]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "celsius", "symbols": ["celsius$subexpression$1"]},
    {"name": "celsius$subexpression$2", "symbols": [/[cC]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "celsius", "symbols": ["celsius$subexpression$2"]},
    {"name": "celsius$subexpression$3", "symbols": [/[cC]/, /[eE]/, /[lL]/, /[sS]/, /[iI]/, /[uU]/, /[sS]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "celsius", "symbols": ["celsius$subexpression$3"]},
    {"name": "mbar$subexpression$1", "symbols": [/[mM]/, /[bB]/, /[aA]/, /[rR]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "mbar", "symbols": ["mbar$subexpression$1"]},
    {"name": "mbar$subexpression$2", "symbols": [/[mM]/, /[iI]/, /[lL]/, /[lL]/, /[iI]/, /[bB]/, /[aA]/, /[rR]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "mbar", "symbols": ["mbar$subexpression$2"]},
    {"name": "mbar$subexpression$3", "symbols": [/[mM]/, /[iI]/, /[lL]/, /[lL]/, /[iI]/, /[bB]/, /[aA]/, /[rR]/, /[sS]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "mbar", "symbols": ["mbar$subexpression$3"]},
    {"name": "dr$subexpression$1$subexpression$1", "symbols": [/[dD]/, /[eE]/, /[dD]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "dr$subexpression$1$ebnf$1", "symbols": [{"literal":"."}], "postprocess": id},
    {"name": "dr$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "dr$subexpression$1", "symbols": ["dr$subexpression$1$subexpression$1", "dr$subexpression$1$ebnf$1"]},
    {"name": "dr$subexpression$1$subexpression$2", "symbols": [/[dD]/, /[eE]/, /[dD]/, /[uU]/, /[cC]/, /[eE]/, /[dD]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "dr$subexpression$1", "symbols": ["dr$subexpression$1$subexpression$2"]},
    {"name": "dr$subexpression$1$subexpression$3", "symbols": [/[dD]/, /[eE]/, /[aA]/, /[dD]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "dr$subexpression$1", "symbols": ["dr$subexpression$1$subexpression$3"]},
    {"name": "dr$subexpression$2$subexpression$1", "symbols": [/[rR]/, /[eE]/, /[cC]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "dr$subexpression$2$ebnf$1", "symbols": [{"literal":"."}], "postprocess": id},
    {"name": "dr$subexpression$2$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "dr$subexpression$2", "symbols": ["dr$subexpression$2$subexpression$1", "dr$subexpression$2$ebnf$1"]},
    {"name": "dr$subexpression$2$subexpression$2", "symbols": [/[rR]/, /[eE]/, /[cC]/, /[kK]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "dr$subexpression$2$ebnf$2", "symbols": [{"literal":"."}], "postprocess": id},
    {"name": "dr$subexpression$2$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "dr$subexpression$2", "symbols": ["dr$subexpression$2$subexpression$2", "dr$subexpression$2$ebnf$2"]},
    {"name": "dr$subexpression$2$subexpression$3", "symbols": [/[rR]/, /[eE]/, /[cC]/, /[kK]/, /[oO]/, /[nN]/, /[iI]/, /[nN]/, /[gG]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "dr$subexpression$2", "symbols": ["dr$subexpression$2$subexpression$3"]},
    {"name": "dr", "symbols": ["dr$subexpression$1", "_", "dr$subexpression$2"]},
    {"name": "dr$subexpression$3", "symbols": [/[dD]/, /[rR]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "dr", "symbols": ["dr$subexpression$3"]},
    {"name": "bearing$subexpression$1", "symbols": [/[hH]/, /[eE]/, /[aA]/, /[dD]/, /[iI]/, /[nN]/, /[gG]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "bearing", "symbols": ["bearing$subexpression$1"]},
    {"name": "bearing$ebnf$1$subexpression$1", "symbols": [/[tT]/, /[rR]/, /[uU]/, /[eE]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "bearing$ebnf$1", "symbols": ["bearing$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "bearing$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "bearing$subexpression$2", "symbols": [/[bB]/, /[eE]/, /[aA]/, /[rR]/, /[iI]/, /[nN]/, /[gG]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "bearing", "symbols": ["bearing$ebnf$1", "_", "bearing$subexpression$2"]},
    {"name": "knot$subexpression$1", "symbols": [/[kK]/, /[nN]/, /[oO]/, /[tT]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "knot", "symbols": ["knot$subexpression$1"]},
    {"name": "knot$subexpression$2", "symbols": [/[kK]/, /[nN]/, /[oO]/, /[tT]/, /[sS]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "knot", "symbols": ["knot$subexpression$2"]},
    {"name": "knot$subexpression$3", "symbols": [/[kK]/, /[nN]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "knot", "symbols": ["knot$subexpression$3"]},
    {"name": "alt$subexpression$1", "symbols": [/[aA]/, /[lL]/, /[tT]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "alt$ebnf$1$subexpression$1", "symbols": [/[iI]/, /[tT]/, /[uU]/, /[dD]/, /[eE]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "alt$ebnf$1", "symbols": ["alt$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "alt$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "alt", "symbols": ["alt$subexpression$1", "alt$ebnf$1"]},
    {"name": "alt$subexpression$2", "symbols": [/[aA]/, /[nN]/, /[gG]/, /[lL]/, /[eE]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "alt", "symbols": ["alt$subexpression$2"]},
    {"name": "object$subexpression$1", "symbols": [/[sS]/, /[tT]/, /[aA]/, /[rR]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "object", "symbols": ["object$subexpression$1"]},
    {"name": "object$subexpression$2", "symbols": [/[pP]/, /[lL]/, /[aA]/, /[nN]/, /[eE]/, /[tT]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "object", "symbols": ["object$subexpression$2"]},
    {"name": "object$subexpression$3", "symbols": [/[mM]/, /[oO]/, /[oO]/, /[nN]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "object", "symbols": ["object$subexpression$3"]},
    {"name": "object$subexpression$4", "symbols": [/[sS]/, /[uU]/, /[nN]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "object", "symbols": ["object$subexpression$4"]},
    {"name": "object$subexpression$5", "symbols": [/[bB]/, /[oO]/, /[dD]/, /[yY]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "object", "symbols": ["object$subexpression$5"]},
    {"name": "object$subexpression$6", "symbols": [/[sS]/, /[iI]/, /[gG]/, /[hH]/, /[tT]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "object", "symbols": ["object$subexpression$6"]},
    {"name": "object$subexpression$7", "symbols": [/[oO]/, /[bB]/, /[jJ]/, /[eE]/, /[cC]/, /[tT]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "object", "symbols": ["object$subexpression$7"]},
    {"name": "object$subexpression$8", "symbols": [/[cC]/, /[eE]/, /[lL]/, /[eE]/, /[sS]/, /[tT]/, /[iI]/, /[aA]/, /[lL]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "object", "symbols": ["object$subexpression$8"]},
    {"name": "object$subexpression$9", "symbols": [/[cC]/, /[eE]/, /[lL]/, /[eE]/, /[sS]/, /[tT]/, /[iI]/, /[aA]/, /[lL]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "object$subexpression$10", "symbols": [/[bB]/, /[oO]/, /[dD]/, /[yY]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "object", "symbols": ["object$subexpression$9", "_", "object$subexpression$10"]},
    {"name": "object$subexpression$11", "symbols": [/[tT]/, /[aA]/, /[rR]/, /[gG]/, /[eE]/, /[tT]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "object", "symbols": ["object$subexpression$11"]},
    {"name": "km$subexpression$1", "symbols": [/[kK]/, /[mM]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "km", "symbols": ["km$subexpression$1"]},
    {"name": "km$subexpression$2", "symbols": [/[kK]/, /[iI]/, /[lL]/, /[oO]/, /[mM]/, /[eE]/, /[tT]/, /[eE]/, /[rR]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "km", "symbols": ["km$subexpression$2"]},
    {"name": "km$subexpression$3", "symbols": [/[kK]/, /[iI]/, /[lL]/, /[oO]/, /[mM]/, /[eE]/, /[tT]/, /[eE]/, /[rR]/, /[sS]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "km", "symbols": ["km$subexpression$3"]},
    {"name": "km$subexpression$4", "symbols": [/[kK]/, /[iI]/, /[lL]/, /[oO]/, /[mM]/, /[eE]/, /[tT]/, /[rR]/, /[eE]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "km", "symbols": ["km$subexpression$4"]},
    {"name": "km$subexpression$5", "symbols": [/[kK]/, /[iI]/, /[lL]/, /[oO]/, /[mM]/, /[eE]/, /[tT]/, /[rR]/, /[eE]/, /[sS]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "km", "symbols": ["km$subexpression$5"]},
    {"name": "word$ebnf$1", "symbols": [/[^\n\r\#]/]},
    {"name": "word$ebnf$1", "symbols": ["word$ebnf$1", /[^\n\r\#]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "word", "symbols": ["word$ebnf$1"], "postprocess": d=> d[0].join('')},
    {"name": "float$ebnf$1$subexpression$1$ebnf$1", "symbols": ["num"], "postprocess": id},
    {"name": "float$ebnf$1$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "float$ebnf$1$subexpression$1", "symbols": [{"literal":"."}, "float$ebnf$1$subexpression$1$ebnf$1"]},
    {"name": "float$ebnf$1", "symbols": ["float$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "float$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "float", "symbols": ["num", "float$ebnf$1"], "postprocess": d=> parseFloat(`${d[0]}.${(d[1]&&d[1][1]?d[1][1]:0)}`)},
    {"name": "int", "symbols": ["num"], "postprocess": d=> parseInt(d[0],10)},
    {"name": "num$ebnf$1", "symbols": [/[0-9]/]},
    {"name": "num$ebnf$1", "symbols": ["num$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "num", "symbols": ["num$ebnf$1"], "postprocess": d=> d[0].join('')},
    {"name": "sep", "symbols": [/[^.0-9\n\r\#]/], "postprocess": d=> null},
    {"name": "break$ebnf$1", "symbols": ["comment"], "postprocess": id},
    {"name": "break$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "break", "symbols": ["_", "break$ebnf$1", "nl"], "postprocess": d=> null},
    {"name": "comment$ebnf$1", "symbols": []},
    {"name": "comment$ebnf$1", "symbols": ["comment$ebnf$1", /[^\n\r]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "comment", "symbols": [{"literal":"#"}, "comment$ebnf$1"], "postprocess": d=> null},
    {"name": "nl", "symbols": [/[\n\r]/], "postprocess": d=> null},
    {"name": "_$ebnf$1", "symbols": []},
    {"name": "_$ebnf$1", "symbols": ["_$ebnf$1", /[ \t]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "_", "symbols": ["_$ebnf$1"], "postprocess": d=> null}
];
let ParserStart = "observation";
export default { Lexer, ParserRules, ParserStart };
